### PR TITLE
#6: Added language to request

### PR DESCRIPTION
**Pull request by mariomurrent-softwaresolutions**

### CODE REVIEW

**Comment by csongorkeller** [comment]
Thanks a lot @mariomurrent-softwaresolutions 
Will review it today and release a new version if all perfect.

**Comment by mariomurrent-softwaresolutions** [comment]
No stress - take your time. I tried to adapt it to your style.
So maybe it's not perfect yet

**Comment by mariomurrent-softwaresolutions** [comment]
Any updates on this?

**Comment by csongorkeller** [comment]
Sorry for the late reaction. I was swamped. Let me merge it today in the evening

**Review by csongorkeller — APPROVED** [review]

**Pull request merged**
